
mssql:
    host: KRR-SQL-PACLX02
    database: KRR-PA-MGT-QCRollingMill

rm1:
    firebird:
        host: 10.21.120.114
        database: D:\db_New\Termo.gdb
        dialect: 1
        username: sysdba
        password: masterkey

rm3:
    firebird:
        host: 10.21.124.162
        database: e:\termo\db\TERMOMS3SPC1.FDB
        dialect: 3
        username: sysdba
        password: masterkey
